// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1Bmh15uzcRc3OnsigaKBP50O-PSccaYQ',
    appId: '1:192743206590:web:5f9b510aef910f663378ef',
    messagingSenderId: '192743206590',
    projectId: 'foodilit',
    authDomain: 'foodilit.firebaseapp.com',
    storageBucket: 'foodilit.firebasestorage.app',
    measurementId: 'G-2MNK3NNPCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX_eDxO0TZD3hh_Adj5eMNQB406mbBTFU',
    appId: '1:192743206590:android:d6e1be4069b7faf83378ef',
    messagingSenderId: '192743206590',
    projectId: 'foodilit',
    storageBucket: 'foodilit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxjuKSL6GA3Pme2yO7waXId-y_65XFe8o',
    appId: '1:192743206590:ios:352b37a245f2534d3378ef',
    messagingSenderId: '192743206590',
    projectId: 'foodilit',
    storageBucket: 'foodilit.firebasestorage.app',
    iosBundleId: 'com.example.foodilit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxjuKSL6GA3Pme2yO7waXId-y_65XFe8o',
    appId: '1:192743206590:ios:352b37a245f2534d3378ef',
    messagingSenderId: '192743206590',
    projectId: 'foodilit',
    storageBucket: 'foodilit.firebasestorage.app',
    iosBundleId: 'com.example.foodilit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1Bmh15uzcRc3OnsigaKBP50O-PSccaYQ',
    appId: '1:192743206590:web:3af1abc1243abf973378ef',
    messagingSenderId: '192743206590',
    projectId: 'foodilit',
    authDomain: 'foodilit.firebaseapp.com',
    storageBucket: 'foodilit.firebasestorage.app',
    measurementId: 'G-9P3CH8S14N',
  );
}
